<?php

namespace AppBundle\Repository;

/**
 * ProjectRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProjectRepository extends \Doctrine\ORM\EntityRepository
{
    public function findBySlug($slug)
    {
        //TODO: get real account ID
        return $this->findOneBy(['slug' => $slug, 'account_id' => 1]);
    }
}
